sudo: false
language: perl
perl:
    - "blead"
    - "dev"
    - "5.26"
    - "5.26-thr"
    - "5.24"
    - "5.24-thr"
    - "5.22"
    - "5.22-thr"
    - "5.20"
    - "5.20-thr"
    - "5.18.3"
    - "5.18.3-thr"
    - "5.16"
    - "5.16-thr"
    - "5.14"
    - "5.14-thr"
    - "5.12"
    - "5.12-thr"
    - "5.12"
    - "5.12-thr"
    - "5.10.0"
    - "5.10.0-thr"
    - "5.10.1"
    - "5.10.1-thr"
    - "5.8.4"
    - "5.8.4-thr"
env:
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
matrix:
    include:
        - perl: 5.6.2
    allow_failures:
        - perl: blead

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
  - cpanm Devel::PPPort
  - cpanm Readonly  # so t/magic-readonly.t can run
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j1 $(test-files)
